### ISSUE TITLE
Gulp notify integration?

### ISSUE THREAD

**Issue by Lori2Lori** [callumacrae/gulp-w3cjs#10] opened 2015-03-27 16:00 UTC
Is there any way to use [gulp notify](https://www.npmjs.com/package/gulp-notify) to display validation errors?

**Comment by callumacrae** [comment] 2015-03-27 16:08
Yeah, use gulp-if and check for `file.w3cjs.success`.

**Comment by callumacrae** [comment] 2015-06-09 10:43
Closing, not a bug.

**Closed by callumacrae** 2015-06-09 10:43 UTC

**Comment by stephanoapiolaza** [comment] 2017-07-17 03:48
this is the solution is 
```
.pipe(gulpIf("!<%= file.w3cjs.success %>",notify("There are errors with HTML5")))
```
The trouble is that always throw the notifications
